---
to: "test/screens/<%= h.changeCase.snake(name) %>/<%= h.changeCase.snake(name) %>_test.dart"
unless_exists: true
---
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mocktail/mocktail.dart';
import 'package:taleemmate/blocs/quotes/cubit.dart';
import 'package:taleemmate/blocs/user/cubit.dart';
import 'package:taleemmate/repos/user/user_repo.dart';
import 'package:taleemmate/router/routes.dart';
import 'package:taleemmate/ui/screens/<%= h.changeCase.snake(name) %>/<%= h.changeCase.snake(name) %>.dart';

import '../../helpers/mocks.dart';
import '../../helpers/test_app.dart';

// Generated by `hygen screen new <%= h.changeCase.snake(name) %>`. Flesh out the
// render / interaction / routing assertions — see docs/TESTING.md and the
// `/write-widget-test` skill for the patterns and gotchas.

void main() {
  setUpAll(() => registerFallbackValue(<String, dynamic>{}));

  setUp(() {
    setupPlatformMocks();
    // The driving cubit stays real; its repo is mocked via the test seam. Stub
    // whatever methods this screen triggers, e.g.:
    //   when(() => UserRepo.ins.fetch()).thenAnswer((_) async => TestUser.rawJson());
    UserRepo.ins = MockUserRepo();
  });

  Future<void> pump<%= h.changeCase.pascal(name) %>(WidgetTester tester) async {
    // Tall surface so an un-scrolled Column never overflows in tests.
    await tester.binding.setSurfaceSize(const Size(1200, 2600));
    addTearDown(() => tester.binding.setSurfaceSize(null));

    final userCubit = UserCubit();
    addTearDown(userCubit.close);
    final quotesCubit = QuotesCubit();
    addTearDown(quotesCubit.close);
    final libraryCubit = FakeLibraryCubit();
    addTearDown(libraryCubit.close);
    final chatCubit = FakeChatCubit();
    addTearDown(chatCubit.close);
    final planCubit = FakePlanCubit();
    addTearDown(planCubit.close);

    await tester.pumpWidget(
      TestApp(
        initialRoute: AppRoutes.<%= h.changeCase.camel(name) %>,
        userCubit: userCubit,
        quotesCubit: quotesCubit,
        libraryCubit: libraryCubit,
        chatCubit: chatCubit,
        planCubit: planCubit,
        routes: {
          ...stubRoutes,
          AppRoutes.<%= h.changeCase.camel(name) %>: (_) =>
              const <%= h.changeCase.pascal(name) %>Screen(),
        },
      ),
    );
    await tester.pump(const Duration(milliseconds: 400));
  }

  testWidgets('renders', (tester) async {
    await pump<%= h.changeCase.pascal(name) %>(tester);

    expect(find.byType(<%= h.changeCase.pascal(name) %>Screen), findsOneWidget);
    // TODO: assert headings / field labels, then add interaction + routing tests.
  });
}
