import java.io.FileInputStream
import java.util.Properties

plugins {
    id("com.android.application")
    id("kotlin-android")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
}

val keystorePropertiesStage = Properties()
val keystorePropertiesStageFile = rootProject.file("keyStage.properties")
if (keystorePropertiesStageFile.exists()) {
    keystorePropertiesStage.load(FileInputStream(keystorePropertiesStageFile))
}

val keystorePropertiesProd = Properties()
val keystorePropertiesProdFile = rootProject.file("keyProd.properties")
if (keystorePropertiesProdFile.exists()) {
    keystorePropertiesProd.load(FileInputStream(keystorePropertiesProdFile))
}

android {
    namespace = "dev.mhmz.taleemmate"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId = "dev.mhmz.taleemmate"
        // You can update the following values to match your application needs.
        // For more information, see: https://flutter.dev/to/review-gradle-config.
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }

    signingConfigs {
        if (keystorePropertiesStageFile.exists()) {
            create("stage") {
                keyAlias = keystorePropertiesStage["keyAlias"] as String
                keyPassword = keystorePropertiesStage["keyPassword"] as String
                storeFile = keystorePropertiesStage["storeFile"]?.let { file(it) }
                storePassword = keystorePropertiesStage["storePassword"] as String
            }
        }
        if (keystorePropertiesProdFile.exists()) {
            create("prod") {
                keyAlias = keystorePropertiesProd["keyAlias"] as String
                keyPassword = keystorePropertiesProd["keyPassword"] as String
                storeFile = keystorePropertiesProd["storeFile"]?.let { file(it) }
                storePassword = keystorePropertiesProd["storePassword"] as String
            }
        }
    }

    buildTypes {
        debug {
            // Debug builds use default debug signing
        }

        release {
            signingConfig = null
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
        }
    }
}

flutter {
    source = "../.."
}
// ----- BEGIN flavorDimensions (autogenerated by flutter_flavorizr) -----
apply { from("flavorizr.gradle.kts") }
// ----- END flavorDimensions (autogenerated by flutter_flavorizr) -----